# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install
- xcrun simctl list # list devices

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=9.1' UI=true
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=8.4'
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=9.1' UI=true
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=8.4'

script:
- set -o pipefail
- xcodebuild -workspace Example/FeetInchDelegate.xcworkspace -scheme FeetInchDelegate-Example -sdk iphonesimulator -destination "OS=9.0,name=iPhone 6" clean build | xcpretty -c || true
- xcodebuild -workspace Example/FeetInchDelegate.xcworkspace -scheme FeetInchDelegate-Example -sdk iphonesimulator -destination "OS=9.0,name=iPhone 6" test | xcpretty -c
